// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://depozngjqxfjtgiwyuhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlcG96bmdqcXhmanRnaXd5dWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Mzg2ODMsImV4cCI6MjA3NDMxNDY4M30.2GGuWW2KOf6C3CiC83DHhHSj39R1Xpx3MVWHOHudm2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});